---
skip_commits:
  files:
    - "*.md"
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler
  - bundle install
before_test:
  - ruby -v
  - gem -v
  - bundle -v
build: off
test_script:
  - bundle exec rake ci
environment:
  matrix:
    - ruby_version: "23"
    - ruby_version: "23-x64"
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "25"
    - ruby_version: "25-x64"
    - ruby_version: "26"
    - ruby_version: "26-x64"
matrix:
  allow_failures:
    - ruby_version: "23"
    - ruby_version: "23-x64"
